apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-scheduler-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-default
  template:
    metadata:
      labels:
        app: myapp-default
    spec:
      containers:
      - name: mynginx
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: latency-meter
        image: crischiaro/latency-meter:latest
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
